version: '3.8'

services:
  web1:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: backend-app-1
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=90d
      - APP_NAME=web1
    depends_on:
      - mongo
    networks:
      - app-network

  web2:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: backend-app-2
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=90d
      - APP_NAME=web2
    depends_on:
      - mongo
    networks:
      - app-network

  web3:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: backend-app-3
    restart: unless-stopped
    ports:
      - "3003:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=90d
      - APP_NAME=web3
    depends_on:
      - mongo
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-load-balancer
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - web1
      - web2
      - web3
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27033:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge